branch-defaults:
  default:
    environment: laudai-env
    group_suffix: null
global:
  application_name: laudai-dev
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.7
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
