name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./laudai
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.11"

      - name: Baixa CLI do Elastic BeanStalk
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli --upgrade
          eb --version

      - name: Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Copy application.properties
        run: |
          echo "$env:APPLICATION_PROPERTIES" > src/main/resources/application.properties && \
          cat src/main/resources/application.properties 

      - name: Build app
        run: mvn -DskipTests=true package

      - name: Deploy no Elastic BeanStalk
        run: |
          eb use laudai-java-env-1 && eb status laudai-java-env-1 && eb deploy