name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.11"

      - name: Instalar Dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Testes Unitarios
        run: |
          python test_application.py
    
  deploy:
    needs:
      - build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.11"

      - name: Baixa CLI do Elastic BeanStalk
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli --upgrade
          eb --version

      - name: Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy no Elastic BeanStalk
        run: |
          eb use Laudai-env && eb status Laudai-env && eb deploy